### ISSUE TITLE
still me with more information

### ISSUE THREAD

**Issue by tvidal-34** [fcheslack/libZotero#18]
Dear Faolan,

I have more information regarding the bug https://github.com/fcheslack/libZotero/issues/16 you closed.

First I make a copy of my web application on a server hosted in a hosting company, without any reverse proxy. Still the same.

Then I downloaded both current and v3 zotero API and test with phpexamples script. And I had the same problem.

Then I also captur packet (wireshark) between my web server and zotero API, and I found something about "bad certificate". When opening https://api.zotero.org in Chrome I seen that the certificate is invalide "The site is using outdated security setting".
Then I know that by default curl check for a valid certificate when using https.
So I added "CURLOPT_SSL_VERIFYPEER -> false" in zotero api lib. But then I got a security error.
I also downloaded the api.zotero.org certificate in Firefox, added in the zotero lib as "curl_setopt ($ch, CURLOPT_CAINFO, "PATH_TO/cacert.pem");" but got the same error.

This is where I am now... and I am surprised to be alone getting this error....
As you can see I already spent a lot of time and energy on this... because I like Zotero and don't want to change all my application.

All the best

Thomas

**Comment by fcheslack** [comment]
Who does it say it's verified by when it's using outdated security settings? It should be valid, but we've seen plenty of people with security software or networks intercepting secure connections and having problems because of that. It seems like that shouldn't be the problem with a third party hosting company though. Are you hosting in a country that does intrusive internet filtering?

(FYI, you closed the other issue yourself. I'm not trying to shut down discussion or reporting, even if I'm at a loss for what's causing this.)

**Comment by tvidal-34** [comment]
Hi,

Web servers (my web server and also the web server in the hosting company) are hosted in France. So no filtering !
In wireshark (I'm not an expert in this area) I just saw :
From IP@of_my_server to 54.236.91.231 protocol TLSc1.2 Alert (Level Fatal, description: Unknow CA)
So I don't know if this can be the problem. Just try to find.
Did you try phpexamples on one of your server ? 

And sorry, I didn't realized that I closed the issue.... click on the wrong button !

**Comment by fcheslack** [comment]
You said when opening https://api.zotero.org/ in the browser it had an invalid ticket. That shouldn't be the case unless something is intercepting your connection, so I was asking what provider it said our certificate was from (if you click on the lock icon in your address bar).
https://www.zotero.org/support/kb/ssl_certificate_error has more information on SSL problems that may be related.

I just freshly cloned the repo on my personal server and the php examples work fine.

My best guess is that this started being a problem for you when HSTS was enabled for zotero servers, and for some reason your server is not able to properly get a secure connection (no idea why setting the cert wouldn't work).

**Comment by tvidal-34** [comment]
Hi,
Just one question : can someone with a working version of the API can let me know OS system and Curl version you are running ?
I would like to try with other system and/or Curl library.
Thanks
Thomas

**Comment by fcheslack** [comment]
Ubuntu 14.04 and 14.10, with curl 7.35.0

**Comment by tvidal-34** [comment]
ok ! I set up a test server with Ubuntu 14.01 and curl 7.35.0, and I don't have the same error as before ! :-)
So I'm pretty sure this is a curl problem, I will investigate in that way.
For the moment I have still a blank page but with an error about fullItemArray()
As I am using v3 of the API I think that I have some changes to do in my code !

Anyway.... I feel that I am on the right way.... after 2 or 3 weeks on it !

Thanks to all

Thomas

**Comment by tvidal-34** [comment]
And for the moment, just to let you know that I'm using Debian 7 with curl 7.26 ....
